import { createRouter } from '@tanstack/react-router';

// Import the route tree generated by the TanStack Router Vite plugin
import { routeTree } from './routeTree.gen';

// Create the router instance
export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
});

// Register the router for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
